### ISSUE TITLE
M: Design 2 mm Parts 2016W23

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/v2-Production#11]
- [x] HC: Write → [Features for 2 mm Parts](#issuecomment-216454842)
- [x] Read →  Features Golden Sample #7 
- [x] Check if we have any redesign listed in Trello Cards. If so, link to here and trigger HC for review. → Found nothing
- [x] Design Parts according → [Features for 2 mm Parts](#issuecomment-216454842)
- [x] Change magnet placement to be: 1) Symmetric 2) reduce number of magnets, as we now have magnets on both parts and thus the connection is stronger 3) Allow to mount top cover in all 4 directions
- [x] Trigger HC for Design Review
- [x] Include Design Changes
- [x] Trigger HC for Design Review
- [x] Create Render Previews with HC. Then save on Server, send HC link
- [x] HC: Process and upload render previews
- [x] HC: Chase bobby for review 
- [x] @bcaswelch [Review new design](#issuecomment-221780126) with HC. You need to OK before we can go to sample production! → approved
- [x] @bcaswelch Ultra last chance to review → #7 Features Golden Sample → approved
- [x] change Bottom Cover to 2 mm. Then trigger review HC.
- [x] change Rear Panel to 2 mm. Then trigger review HC.
- [x] change holding parts for Flex Power and AC-Plug to 2 mm. Then trigger review HC.
- [x] change 6 mm part for front so that it can hold a 8 mm Industrial Sandwich Plastic board. Change three holding tabs to include a 4 mm Ø hole to use a 4 mm wood screw to the plastic board. In turn the board can receive 3 mm wood screws to hold any pico ATX PSU that requires mounting to a board.
- [x] Check this summary. Add anything I forgot: →  Revision and Strategy Change Lists #26 
# Reference
- →  Features Golden Sample #7

**Comment by VillageHubertChen** [comment]
# Features for 2 mm Parts

## Quick Snap Top Cover
- New design: One big airflow hole
- 2 mm materials
- magnets on both parts

## Quick Snap Top Filter
- New design: One big airflow hole
- 2 mm materials
- magnets on both parts
- Filter holder squeezes filter between Top Cover and Filter Holder

## Top and bottom cover
- Make two top covers → Black and Red Top Cover
- Miter: 
  - 45° Angle, about 1 mm surface lengths → 0.8 mm deep
  - Both top and bottom cover
- Change to 2 mm strengths. Simplify CNC cuts.
- Top and Bottom cover each is panel form with small parts in cut out of big hole

## No separate small parts
- Move into Top and bottom cover

## Single sided production
- Make all design changes for single sided production
- Housing need to be taller, as we do not cut recess for bracket
- Screw holes in top and bottom frame are countersunk. 
  - If can not cut with CNC, need to do secondary tooling in office with drill press

**Comment by VillageHubertChen** [comment]
# Review the new design
- [x] Make Render Previews of new design and embed into this comment
- [x] @bcaswelch Review this design with HC. Please see lists of benefits

## Benefits new design
- More consistent design, look and feel. Now top grill matches side grill
- Top filter is more easy to clean
- Cleaning of top and side filter is consistent
- Now support all 4 directions when mounting the lid. Logo is always upright!
- Higher contrast logo
- New design allows to fit into manufacturing budget for 129 USD ViCase Mini

## Render Previews

### Standard Front View (preview)

![front-view-b](https://cloud.githubusercontent.com/assets/7278716/15573065/0e0bdd90-2377-11e6-9165-2ca976447220.jpg)

### Standard Rear View (preview)

![rear-view](https://cloud.githubusercontent.com/assets/7278716/15580638/06b1e204-239c-11e6-9a39-8dcc3b62da2b.jpg)

### Filter Assembly (snaps)

![top-cover-filter-assembly-1](https://cloud.githubusercontent.com/assets/7278716/15580682/16828670-239c-11e6-8d8a-d128e8c85772.jpg)
Top cover only, inside view, all 3 parts assembled

![top-cover-filter-assembly-explosion](https://cloud.githubusercontent.com/assets/7278716/15580859/c1eadda0-239c-11e6-8bca-ba1c4936edce.jpg)
Same parts as above, but explosion view

**Comment by bcaswelch** [comment]
Hi Hubert,

These changes all seem great! Looks easy to assemble with a consistent aesthetic. 

1-will I be able to VESA mount this unit to a monitor? I definitely want to test out how it looks and feels on a screen.

**Comment by VillageHubertChen** [comment]
@bcaswelch Hi, great to hear from you. Yes. We are late and the same time we are early. We changed plan to include all changes for mass production. So the unit that you are getting is final design in all regards, features and details. You will be able to mount to a Display with a free VESA mount in the back. We support 75, 100 and 200 mm grid spacing. However, I believe we forgot to put the VESA bracket in there. I will now check the packaging list for final shipping and add it accordingly. So thanks for asking :-)

**Comment by VillageHubertChen** [comment]
@bcaswelch You may be interested in this summary I just wrote:  Revision and Strategy Change Lists → #26
