### ISSUE TITLE
Video Review (4) V²Shop-Midwest

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/v2-Production#38]
- [ ] Create a list of all features of ViPC
- [ ] Find a way to record this session. We will use it for reference when creating product documentation
- [ ] Show ViPC Open and Close Top-Cover, show 4 directions
- [ ] Show ViPC change Top-Cover Color from Black to Red
- [ ] Show changing Filter
- [ ] Show changing Fuse
- [ ] Show ViCase-Access
  - [ ] Power On
  - [ ] Programming LED
  - [ ] LED function
- [ ] Show ViCase-Feet
- [ ] Show ViCase-Remote
- [ ] Show ViCase-Lights (and its remote)
- [ ] Show Assembly Option Flex ATX
- [ ] Show Assembly Option picoATX Power
- [ ] Show Assembly Option big picoATX Power
- [ ] Show two CPU Cooler options
- [ ] Show list of supporting parts on Amazon
  - picoATX
  - big pico ATX
  - 120W AC Adapter
  - 240W AC Adapter
- [ ] create an Epic to turn all this information into Product Pages

**Comment by bcaswelch** [comment]
Sounds clear to me.
