### ISSUE TITLE
Video Review (0) V²Shop-Midwest 2016W23

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/v2-Production#40]
### Preparing Video Conference
- [x] Create a complete list of all features of ViPanel, ViSurge, ViCase-Access
### Video Conference
- Wednesday, June 1st, 8:00 pm LV time, 11 am China time
  Show the following features (not yet a complete list)
- [x] ViPanel PCB and its functions
- [x] ViSurge PCB and its functions
- [x] ViCase-Access PCB and its functions
- [x] Show all cables and their functions
- [x] Show a complete assembled ViPC
- [x] Show all Assembly / Configuration Options
  - [x] Power Options
    - [x] Flex ATX (300W, fan)
    - [x] pico ATX (120W, fan-less)
    - [x] micro ATX (240W, fan-less)
  - [x] CPU Cooling Options
    - [x] ViCase Cooler L
    - [x] ViCase Cooler XL
  - [x] Top Cover Options
    - [x] Black
    - [x] Red
  - [x] ViCase-Chroma (Programmable Color Lights)
  - [x] Disk mounting options
- [x] Talk about floppy nature of Side Grill. Make sure this is OK or discuss if need any changes.
### Post Video Conference
-  → Create Last Engineering Change List #44 
- → [ViCase Accessory Video G1 #127](https://github.com/V-Squared/V-Squared.github.io/issues/127)

**Comment by VillageHubertChen** [comment]
# Discussion on Silent and 0dB PC
- [x] Ultra Low Fan speed option
- http://www.amazon.com/HDPLEX-Internal-Power-Adapter-Output/dp/B00QSRBPB2
- http://www.amazon.com/Original-PA-9E-Replacement-adapter-Notebook/dp/B00AVMYMUG
- http://www.amazon.com/HDPLEX-DC-ATX-Power-Supply-16V-24V/dp/B00KVWHUXW
- www.hd-plex.com (check if they have a bigger than 160W option, this site is blocked in China)

**Comment by bcaswelch** [comment]
Agree with the HD-Plex power supplies, seem like the best option in terms of space and noise. People won't need more than 250w for a SFF computer.

**Comment by bcaswelch** [comment]
Will you have an AiO converter to show?

**Comment by VillageHubertChen** [comment]
# Answering bcaswelch
1. **HD-Plex** we are designing them in. It is very hard work because it is really tight and cooling airflow is complex.
2. **AiO converter:** I assume you mean the "ViCase-Stand", that is the Display Stand that also holds ViCase, Keyboard and Mouse? I have added it to the list. Thanks for the reminder.
