### ISSUE TITLE
(Moved. Do not use!) Shipment 001 Core → V²Shop-Midwest

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/v2-Production#46]
# Tasks
- [ ] HC: Create Proposal of contents of shipment
- [ ] TC: Please write your shipping address into the comment
- [ ] TC: Check if you want anything else, trigger BC and KC to check too
  - write the result into comment. This will trigger me to begin prepping the shipment
- [ ] ML: Create Order in Taobao. Trigger HC approval before order
- [ ] HC: Go to office and cut Aluminum Sample
- [ ] ML: Prepare shipment, trigger HC for review
- [ ] ML: Ship to address TC posted in comment
- [ ] HC: Close this Issue. Create new Issue on Review this Shipment in Backlog
# Proposal of contents of shipment
- [ ] Anodized Aluminum Sample for testing laser engraving as per Karen's request
  This will be cut off from a black ViDock case. If we can not find black we will use natural anodized
- [ ] ViCase Cooler L
- [ ] ViCase Cooler XL
- [ ] ViCase-Chroma (Strip, PSU, Remote Control. Could be the set we have)
- [ ] ViCase-Control
- [ ] Rubber Feet Samples (both types)
- [ ] Rubber Grommets Samples
- [ ] Screw Samples 
# About Screw and Rubber Samples
- Purpose is to let V²Shop check if there is anything not OK
- Package each sample into a small Zip Lock Bag. 5 pcs will be sufficient. No label needed.
# Separate Shipment ?

As per vote V²Shop-Midwest wants to put priority to put ViCase Gold Sample to production. Best time slot to BTL ViPanel would be once we are waiting for samples to return from CNC Shops. If other parts are available earlier, we should discuss making two shipments.
- [ ] Assembled ViPanel-V² & ViPanel-ATX

**Comment by VillageHubertChen** [comment]
Issue moved to [V-Squared/V-Squared.github.io #131](https://github.com/V-Squared/V-Squared.github.io/issues/131) via [**ZenHub.io**](https://www.zenhub.io/)
