### ISSUE TITLE
M: CNC-Cut Fixture for 2 mm Parts

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/v2-Production#47]
# Tasks
- [x] Write the Trello card → [Trello►Fixture for cutting 2 mm Parts](https://trello.com/c/wTKSog5L/543-fixture-for-cutting-2-mm-parts). Trigger HC for Review
  - [ ] HC: Review 
- [ ] Choose the CNC shop
  - [x] Write Trello Card on how to choose CNC shop (we should have some writing already). Trigger HC for review.
  - [x] HC: Review Procedure choose CNC shop
- [x] Buy the things need for the fixture
  - [x] Compile Shopping List in Trello Card → ???
  - [x] Create Shopping List in Taoabo. Trigger HC for review
  - [x] Review
- [ ] Cut the fixture in the CNC shop
- [ ] Assemble the fixture (check screw inserts fit)

**Comment by VillageMichaelLin** [comment]
@VillageHubertChen Please review → [Trello►Fixture for cutting 2 mm Parts](https://trello.com/c/wTKSog5L/543-fixture-for-cutting-2-mm-parts)

**Comment by VillageMichaelLin** [comment]
- [x] Write the trello card for this fixture
- [ ] Choose the CNC shop
- [ ] Buy the things need for the fixture
- [ ] Cut the fixture in the CNC shop
- [ ] Assembly the fixture

**Comment by VillageHubertChen** [comment]
Dear Michael. Please check how I moved the content for the task list to the top comment and how I edit the trigger of you to me in your comment. Please check with me after kick off meeting in case I have not reviewed the Trello Card by 3 pm.

**Comment by VillageMichaelLin** [comment]
@VillageHubertChen Please review → [Trello►How to choose the CNC shop](https://trello.com/c/zKO3eb88/545-how-to-choose-cnc-shop)

**Comment by VillageHubertChen** [comment]
@VillageMichaelLin I reviewed and edited → [Trello►How to choose the CNC shop](https://trello.com/c/zKO3eb88/545-how-to-choose-cnc-shop). Please see the comment.
