### ISSUE TITLE
M: Redesign Fixture new Method

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/v2-Production#49]
# Tasks
- [x] Redo the Fixture Design in CAD as per below spec
- [x] Change Workflow as per below spec
- [ ] Redo the Fixture Design in CamBam as per below spec
- [x] Create a list of all G-Code and M-Code that you used
# Changes
## CAD
- [x] Move all Primitive corner points into Grid of 1.0 mm
  - Where can not, move to grid of 0.5 mm
  - where can not, discuss with HC
## Workflow
- [x] Export DXF directly from SolidWorks
- [x] Export STL directly from SolidWorks. Use new quality Settings.
## In CamBam:
- Make comment to Tool
- Import DXF into Layer: Reference
- Draw all drawings onto designated layers
  - Drill
  - Outline
  - Pockets
-  Snap back all Primitive Coordinates into the Grid
- Check G-Code for every feature
  - Is it most simple G-Code?
  - Coordinates in Grid?
