### ISSUE TITLE
E: Design ViPanel & ViSurge 05.05.

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/v2-Production#5]
- [x] Fix → [Safety Issue of Fuse Holder](#issuecomment-219592890)
  - [x] Create snap shot of new design, send to HC to publish in Issue for review by BC
  - [x] @bcaswelch Review new design
- [x] Complete Design
- [x] Trigger review to HC

**Comment by VillageHubertChen** [comment]
# Fix Safety Issue of Fuse Holder

## Problem

After we received all the parts we found that the fuse holder allows for touching the contacts. In case the power cable is still connected to the ViCase this means the user can electrocute himself. 

## Solution
- Remove Fuse from Outside of Case
- Move fuse to inside
- Add Label to warn and explain

## Additional improvements

Solving this problem requires a redesign of a big portion of ViSurge anyways, so we can add other improvements on our backlog list:
- Make Varistor User Replaceable
- Add Spare Fuse and Varistor Holder (Ziplock bag taped to side wall)

## Why redesigning now
- Issue is very important as it involves safety of user
- If we delayed the Redesign, we would need to change the following later:
  - Rear-Panel
  - ViSurge Cover
  - ViSurge Label
  - Features of ViSurge
  - Images documenting ViSurge
  - Description on how to use ViSurge

# Snap Shots

## Rear Panel Before

![rear-panel-before](https://cloud.githubusercontent.com/assets/7278716/15366890/1b549592-1d59-11e6-9bed-72b2b5b3650a.png)

This is the design before we fixed the problem: We placed the fuse holder on the rear panel of the case. The thinking was to make the fuse easy replaceable. Unfortunately only when receiving the fuse holder component we realized that you can touch the fuse contacts when replacing the fuse and thus you could electrocute yourself. A possible workaround is to place a warning label on the rear panel, but it would be not good looking and scary.

## Rear Panel Now

![rear-panel-now](https://cloud.githubusercontent.com/assets/7278716/15366901/24c7a876-1d59-11e6-97be-290154723fa0.png)

In the new design we moved the Fuse Holder inside the housing.

## ViSurge Top View Build In

![visurge-topview-buildin-b](https://cloud.githubusercontent.com/assets/7278716/15366903/2b85a4d8-1d59-11e6-9a39-5f1e8c187bd9.png)

A warning label inside the computer housing is neither ugly not scary. There is also another benefit that it is more intuitive and common sense to unplug the power cable when opening a case. At the very least the user has been warned that replacing fuse involved high voltage and that he shall unplug the power cable. We even point to where that would be. What I find particular useful is that we include and even point to the needed replacement parts.

## Placement of Spares

![placement-of-spares](https://cloud.githubusercontent.com/assets/7278716/15366907/31292f5e-1d59-11e6-9953-89af2f4ac97a.png)

A better view point to see the replacement parts. They are contained in a clear 3 x 5 cm zip lock bag and taped to the inside of the housing. Dimensions of housing and bag have been chosen that you can not see it from the outside of the housing to not impair cosmetics.

## Bag with Spares <a name="bag-with-spares">

![bag-with-spares-b](https://cloud.githubusercontent.com/assets/7278716/15451816/a9f71d04-2008-11e6-9d91-c61d066cda17.png)

We include 3 fuses, one Varistor and several spare screws. It is unlikely that the user ever needs to replace the Varistor. But in case a very powerful surge knocked out the varistor in the surge protector you can replace it by yourself versus buying a new surge protector. Placing the bag inside the ViCase ensures that by the time you need the spare parts you can find them.

**Comment by bcaswelch** [comment]
Good catch, definitely an issue that needs resolving. Let me know whenever you upload the snaps and I will make to sure notice this when I get my sample case.

**Comment by VillageHubertChen** [comment]
Hi Bobby, we will add the snapshots in a few hours. It would be great if you can review ASAP. This is the last step before putting the PCB to production.

Thanks very much for your appreciation! We were a bit frustrated on this setback, but it is important to us that ViCase is very safe. The new design also adds the very nice feature of intuitive instructions on a label and user replaceable spare parts. To my knowledge this is the first surge protector that the user can repair himself after a powerful surge burned it out.

**Comment by VillageHubertChen** [comment]
@bcaswelch . I uploaded the images for the new design. Please review. We can not work tomorrow due to construction. I will check in the day after tomorrow.

**Comment by bcaswelch** [comment]
Hi Hubert, these snapshots look great! Seems like a much safer alternative while also keeping the vicase stylish. I think the text will be very helpful, and anyone trying to change the fuse will most definitely read it.
-Changing the fuse is a feature a would highlight, because I could see a lot of people not knowing you supply everything needed and going out to a store to try and fix it.
-Is it ok to keep a plastic bag in a hot computer case? I think its a great location for storage and if its fine in there, no need to change?

**Comment by VillageHubertChen** [comment]
Hi Bobby, thanks for the feedback.
1. I agree we should highlight in the user documentation or even marketing materials that we include even the user replaceable parts. Lets work on that when we make the product web site. You can start thinking about how to market it
2. The air inside the housing is not getting so hot as to affect the plastic bag.

I take your comments than as approval and we will tape out the PCB today. We could not work the last few days because we had construction in the building that was unbelievably loud.

**Comment by bcaswelch** [comment]
1. Yes, I approve of the changes. Self repair is a feature many want / appreciate with computers so this will be a positive message to promote.
2. Okay good, figured it wasnt going to be an issue but thought I'd bring it up just in case. I think its great to keep inside the case because small bags that come with computers ALWAYS get lost. I wonder if the bag could include extra screws/mounting brackets..? 

I'll try to check my email periodically for updates and reply as soon as possible. In other news my LA class has been going wonderfully so far :)

**Comment by VillageHubertChen** [comment]
1. Yep. We should have one Article only focused on all design features regarding self repair. We should promote iFixit and by the time we publish it we should try to get them cross link it. That should help the spirit of iFixitr to have a manufacturer designing a product following iFixit guidelines and bring us some traffic.
2. Great idea on adding spare screws. We will do this right away. 
3. Change of topic: I am realizing that we are spending a huge amount of time on the surge protection and power distribution. It is very, very difficult to make it this small and still follow all safety regulations. At the same time when using ViCase in real life, this makes a big difference in removing the cable clutter that comes with a PC. We need to find a way to bring this message across to get a Return of Investment. This is a very unique selling point :-)

I can not use email, gmail is blocked in China. Is it possible you call me on skype. I really want to talk to you. I am currently spending a lot of time to complete the planning and organization part of the V²Site and would be grateful to double check with you if this is the best use of my time at this moment to prepare selling ViCase.

**Comment by VillageHubertChen** [comment]
we updated the image [Bag with Spare Parts](#bag-with-spares) as per your suggestions and added spare screws. Note: We are not using any spare brackets that might get lost.
